# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mvp_grasping/NextViewpointRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class NextViewpointRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "mvp_grasping/NextViewpointRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NextViewpointRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mvp_grasping/NextViewpointResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import mvp_grasping.msg

class NextViewpointResponse(genpy.Message):
  _md5sum = "b48658ae3de44f598cf8af1346003291"
  _type = "mvp_grasping/NextViewpointResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool success
geometry_msgs/Twist velocity_cmd
mvp_grasping/Grasp best_grasp
uint32 no_viewpoints


================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: mvp_grasping/Grasp
geometry_msgs/Pose pose
float32 quality
float32 entropy
float32 width

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['success','velocity_cmd','best_grasp','no_viewpoints']
  _slot_types = ['bool','geometry_msgs/Twist','mvp_grasping/Grasp','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       success,velocity_cmd,best_grasp,no_viewpoints

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NextViewpointResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.success is None:
        self.success = False
      if self.velocity_cmd is None:
        self.velocity_cmd = geometry_msgs.msg.Twist()
      if self.best_grasp is None:
        self.best_grasp = mvp_grasping.msg.Grasp()
      if self.no_viewpoints is None:
        self.no_viewpoints = 0
    else:
      self.success = False
      self.velocity_cmd = geometry_msgs.msg.Twist()
      self.best_grasp = mvp_grasping.msg.Grasp()
      self.no_viewpoints = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B13d3fI().pack(_x.success, _x.velocity_cmd.linear.x, _x.velocity_cmd.linear.y, _x.velocity_cmd.linear.z, _x.velocity_cmd.angular.x, _x.velocity_cmd.angular.y, _x.velocity_cmd.angular.z, _x.best_grasp.pose.position.x, _x.best_grasp.pose.position.y, _x.best_grasp.pose.position.z, _x.best_grasp.pose.orientation.x, _x.best_grasp.pose.orientation.y, _x.best_grasp.pose.orientation.z, _x.best_grasp.pose.orientation.w, _x.best_grasp.quality, _x.best_grasp.entropy, _x.best_grasp.width, _x.no_viewpoints))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.velocity_cmd is None:
        self.velocity_cmd = geometry_msgs.msg.Twist()
      if self.best_grasp is None:
        self.best_grasp = mvp_grasping.msg.Grasp()
      end = 0
      _x = self
      start = end
      end += 121
      (_x.success, _x.velocity_cmd.linear.x, _x.velocity_cmd.linear.y, _x.velocity_cmd.linear.z, _x.velocity_cmd.angular.x, _x.velocity_cmd.angular.y, _x.velocity_cmd.angular.z, _x.best_grasp.pose.position.x, _x.best_grasp.pose.position.y, _x.best_grasp.pose.position.z, _x.best_grasp.pose.orientation.x, _x.best_grasp.pose.orientation.y, _x.best_grasp.pose.orientation.z, _x.best_grasp.pose.orientation.w, _x.best_grasp.quality, _x.best_grasp.entropy, _x.best_grasp.width, _x.no_viewpoints,) = _get_struct_B13d3fI().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B13d3fI().pack(_x.success, _x.velocity_cmd.linear.x, _x.velocity_cmd.linear.y, _x.velocity_cmd.linear.z, _x.velocity_cmd.angular.x, _x.velocity_cmd.angular.y, _x.velocity_cmd.angular.z, _x.best_grasp.pose.position.x, _x.best_grasp.pose.position.y, _x.best_grasp.pose.position.z, _x.best_grasp.pose.orientation.x, _x.best_grasp.pose.orientation.y, _x.best_grasp.pose.orientation.z, _x.best_grasp.pose.orientation.w, _x.best_grasp.quality, _x.best_grasp.entropy, _x.best_grasp.width, _x.no_viewpoints))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.velocity_cmd is None:
        self.velocity_cmd = geometry_msgs.msg.Twist()
      if self.best_grasp is None:
        self.best_grasp = mvp_grasping.msg.Grasp()
      end = 0
      _x = self
      start = end
      end += 121
      (_x.success, _x.velocity_cmd.linear.x, _x.velocity_cmd.linear.y, _x.velocity_cmd.linear.z, _x.velocity_cmd.angular.x, _x.velocity_cmd.angular.y, _x.velocity_cmd.angular.z, _x.best_grasp.pose.position.x, _x.best_grasp.pose.position.y, _x.best_grasp.pose.position.z, _x.best_grasp.pose.orientation.x, _x.best_grasp.pose.orientation.y, _x.best_grasp.pose.orientation.z, _x.best_grasp.pose.orientation.w, _x.best_grasp.quality, _x.best_grasp.entropy, _x.best_grasp.width, _x.no_viewpoints,) = _get_struct_B13d3fI().unpack(str[start:end])
      self.success = bool(self.success)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B13d3fI = None
def _get_struct_B13d3fI():
    global _struct_B13d3fI
    if _struct_B13d3fI is None:
        _struct_B13d3fI = struct.Struct("<B13d3fI")
    return _struct_B13d3fI
class NextViewpoint(object):
  _type          = 'mvp_grasping/NextViewpoint'
  _md5sum = 'b48658ae3de44f598cf8af1346003291'
  _request_class  = NextViewpointRequest
  _response_class = NextViewpointResponse
