// Generated by gencpp from file mvp_grasping/AddFailurePointResponse.msg
// DO NOT EDIT!


#ifndef MVP_GRASPING_MESSAGE_ADDFAILUREPOINTRESPONSE_H
#define MVP_GRASPING_MESSAGE_ADDFAILUREPOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mvp_grasping
{
template <class ContainerAllocator>
struct AddFailurePointResponse_
{
  typedef AddFailurePointResponse_<ContainerAllocator> Type;

  AddFailurePointResponse_()
    {
    }
  AddFailurePointResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddFailurePointResponse_

typedef ::mvp_grasping::AddFailurePointResponse_<std::allocator<void> > AddFailurePointResponse;

typedef boost::shared_ptr< ::mvp_grasping::AddFailurePointResponse > AddFailurePointResponsePtr;
typedef boost::shared_ptr< ::mvp_grasping::AddFailurePointResponse const> AddFailurePointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace mvp_grasping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvp_grasping/AddFailurePointResponse";
  }

  static const char* value(const ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddFailurePointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mvp_grasping::AddFailurePointResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MVP_GRASPING_MESSAGE_ADDFAILUREPOINTRESPONSE_H
