// Generated by gencpp from file mvp_grasping/AddFailurePoint.msg
// DO NOT EDIT!


#ifndef MVP_GRASPING_MESSAGE_ADDFAILUREPOINT_H
#define MVP_GRASPING_MESSAGE_ADDFAILUREPOINT_H

#include <ros/service_traits.h>


#include <mvp_grasping/AddFailurePointRequest.h>
#include <mvp_grasping/AddFailurePointResponse.h>


namespace mvp_grasping
{

struct AddFailurePoint
{

typedef AddFailurePointRequest Request;
typedef AddFailurePointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddFailurePoint
} // namespace mvp_grasping


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mvp_grasping::AddFailurePoint > {
  static const char* value()
  {
    return "a7c84ff13976aa04656e56e300124444";
  }

  static const char* value(const ::mvp_grasping::AddFailurePoint&) { return value(); }
};

template<>
struct DataType< ::mvp_grasping::AddFailurePoint > {
  static const char* value()
  {
    return "mvp_grasping/AddFailurePoint";
  }

  static const char* value(const ::mvp_grasping::AddFailurePoint&) { return value(); }
};


// service_traits::MD5Sum< ::mvp_grasping::AddFailurePointRequest> should match
// service_traits::MD5Sum< ::mvp_grasping::AddFailurePoint >
template<>
struct MD5Sum< ::mvp_grasping::AddFailurePointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mvp_grasping::AddFailurePoint >::value();
  }
  static const char* value(const ::mvp_grasping::AddFailurePointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvp_grasping::AddFailurePointRequest> should match
// service_traits::DataType< ::mvp_grasping::AddFailurePoint >
template<>
struct DataType< ::mvp_grasping::AddFailurePointRequest>
{
  static const char* value()
  {
    return DataType< ::mvp_grasping::AddFailurePoint >::value();
  }
  static const char* value(const ::mvp_grasping::AddFailurePointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mvp_grasping::AddFailurePointResponse> should match
// service_traits::MD5Sum< ::mvp_grasping::AddFailurePoint >
template<>
struct MD5Sum< ::mvp_grasping::AddFailurePointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mvp_grasping::AddFailurePoint >::value();
  }
  static const char* value(const ::mvp_grasping::AddFailurePointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvp_grasping::AddFailurePointResponse> should match
// service_traits::DataType< ::mvp_grasping::AddFailurePoint >
template<>
struct DataType< ::mvp_grasping::AddFailurePointResponse>
{
  static const char* value()
  {
    return DataType< ::mvp_grasping::AddFailurePoint >::value();
  }
  static const char* value(const ::mvp_grasping::AddFailurePointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MVP_GRASPING_MESSAGE_ADDFAILUREPOINT_H
