// Generated by gencpp from file mvp_grasping/Grasp.msg
// DO NOT EDIT!


#ifndef MVP_GRASPING_MESSAGE_GRASP_H
#define MVP_GRASPING_MESSAGE_GRASP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace mvp_grasping
{
template <class ContainerAllocator>
struct Grasp_
{
  typedef Grasp_<ContainerAllocator> Type;

  Grasp_()
    : pose()
    , quality(0.0)
    , entropy(0.0)
    , width(0.0)  {
    }
  Grasp_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , quality(0.0)
    , entropy(0.0)
    , width(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef float _quality_type;
  _quality_type quality;

   typedef float _entropy_type;
  _entropy_type entropy;

   typedef float _width_type;
  _width_type width;





  typedef boost::shared_ptr< ::mvp_grasping::Grasp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mvp_grasping::Grasp_<ContainerAllocator> const> ConstPtr;

}; // struct Grasp_

typedef ::mvp_grasping::Grasp_<std::allocator<void> > Grasp;

typedef boost::shared_ptr< ::mvp_grasping::Grasp > GraspPtr;
typedef boost::shared_ptr< ::mvp_grasping::Grasp const> GraspConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mvp_grasping::Grasp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mvp_grasping::Grasp_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mvp_grasping::Grasp_<ContainerAllocator1> & lhs, const ::mvp_grasping::Grasp_<ContainerAllocator2> & rhs)
{
  return lhs.pose == rhs.pose &&
    lhs.quality == rhs.quality &&
    lhs.entropy == rhs.entropy &&
    lhs.width == rhs.width;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mvp_grasping::Grasp_<ContainerAllocator1> & lhs, const ::mvp_grasping::Grasp_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mvp_grasping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mvp_grasping::Grasp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mvp_grasping::Grasp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvp_grasping::Grasp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mvp_grasping::Grasp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_grasping::Grasp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mvp_grasping::Grasp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mvp_grasping::Grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90c9438303b271d3a45352442c7a7579";
  }

  static const char* value(const ::mvp_grasping::Grasp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90c9438303b271d3ULL;
  static const uint64_t static_value2 = 0xa45352442c7a7579ULL;
};

template<class ContainerAllocator>
struct DataType< ::mvp_grasping::Grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mvp_grasping/Grasp";
  }

  static const char* value(const ::mvp_grasping::Grasp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mvp_grasping::Grasp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n"
"float32 quality\n"
"float32 entropy\n"
"float32 width\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::mvp_grasping::Grasp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mvp_grasping::Grasp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.quality);
      stream.next(m.entropy);
      stream.next(m.width);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Grasp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mvp_grasping::Grasp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mvp_grasping::Grasp_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "quality: ";
    Printer<float>::stream(s, indent + "  ", v.quality);
    s << indent << "entropy: ";
    Printer<float>::stream(s, indent + "  ", v.entropy);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MVP_GRASPING_MESSAGE_GRASP_H
