// Generated by gencpp from file mvp_grasping/NextViewpoint.msg
// DO NOT EDIT!


#ifndef MVP_GRASPING_MESSAGE_NEXTVIEWPOINT_H
#define MVP_GRASPING_MESSAGE_NEXTVIEWPOINT_H

#include <ros/service_traits.h>


#include <mvp_grasping/NextViewpointRequest.h>
#include <mvp_grasping/NextViewpointResponse.h>


namespace mvp_grasping
{

struct NextViewpoint
{

typedef NextViewpointRequest Request;
typedef NextViewpointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NextViewpoint
} // namespace mvp_grasping


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mvp_grasping::NextViewpoint > {
  static const char* value()
  {
    return "b48658ae3de44f598cf8af1346003291";
  }

  static const char* value(const ::mvp_grasping::NextViewpoint&) { return value(); }
};

template<>
struct DataType< ::mvp_grasping::NextViewpoint > {
  static const char* value()
  {
    return "mvp_grasping/NextViewpoint";
  }

  static const char* value(const ::mvp_grasping::NextViewpoint&) { return value(); }
};


// service_traits::MD5Sum< ::mvp_grasping::NextViewpointRequest> should match
// service_traits::MD5Sum< ::mvp_grasping::NextViewpoint >
template<>
struct MD5Sum< ::mvp_grasping::NextViewpointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mvp_grasping::NextViewpoint >::value();
  }
  static const char* value(const ::mvp_grasping::NextViewpointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvp_grasping::NextViewpointRequest> should match
// service_traits::DataType< ::mvp_grasping::NextViewpoint >
template<>
struct DataType< ::mvp_grasping::NextViewpointRequest>
{
  static const char* value()
  {
    return DataType< ::mvp_grasping::NextViewpoint >::value();
  }
  static const char* value(const ::mvp_grasping::NextViewpointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mvp_grasping::NextViewpointResponse> should match
// service_traits::MD5Sum< ::mvp_grasping::NextViewpoint >
template<>
struct MD5Sum< ::mvp_grasping::NextViewpointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mvp_grasping::NextViewpoint >::value();
  }
  static const char* value(const ::mvp_grasping::NextViewpointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mvp_grasping::NextViewpointResponse> should match
// service_traits::DataType< ::mvp_grasping::NextViewpoint >
template<>
struct DataType< ::mvp_grasping::NextViewpointResponse>
{
  static const char* value()
  {
    return DataType< ::mvp_grasping::NextViewpoint >::value();
  }
  static const char* value(const ::mvp_grasping::NextViewpointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MVP_GRASPING_MESSAGE_NEXTVIEWPOINT_H
