(cl:defpackage mvp_grasping-srv
  (:use )
  (:export
   "ADDFAILUREPOINT"
   "<ADDFAILUREPOINT-REQUEST>"
   "ADDFAILUREPOINT-REQUEST"
   "<ADDFAILUREPOINT-RESPONSE>"
   "ADDFAILUREPOINT-RESPONSE"
   "NEXTVIEWPOINT"
   "<NEXTVIEWPOINT-REQUEST>"
   "NEXTVIEWPOINT-REQUEST"
   "<NEXTVIEWPOINT-RESPONSE>"
   "NEXTVIEWPOINT-RESPONSE"
  ))

